---
title: "Анализ значимых событий "
output: html_document
header-includes:
- \usepackage[russian]{babel}
---

Будем рассматривать события поискового рынка за сентябрь - ноябрь 2015 года. Для простоты сосредочимся на новостях, связанных с Яндекс и Google, но также будем рассматривать наиболее значимые события рынка, не связанные с этими компаниями.

# Сентябрь

* Яндекс будет понижать сайты, злоупотребляющие продажей SEO-ссылок (источник: блог для вебмастеров Яндекса).

* Яндекс тестирует новый подход к определению релевантности документов (эксперементирующий подход) (источник: Searchengines.ru)

# Октябрь

* ФАС обязала Google разрешить предустановку приложений Яндекса на Android-смартфоны (источник: ФАС)

* Соцсеть Facebook запустила полноценный поиск по всем опубликованным публичным заметкам (источник: Facebook.com)

* Google обновил поисковый алгоритм – теперь все опасные для пользователей сайты будут исключены из выдачи (источник: Google Webmaster Central Blog)

* Яндекс увеличил долю в Турции до 7% за счёт контракта с футболистами «Фенербахче» (источник: конференция Яндекса по итогам третьего квартала 2015 года)

* Yahoo будет показывать результаты поиска от Google (источник: Searchengineland.com)

* Яндекс станет стандартным поисковиком в Windows 10 для России, Турции и ряда стран СНГ (источник: vc.ru)

* Google запустил сервис быстрого просмотра статей прямо в результатах мобильного поиска (источник: TechCrunch)

# Ноябрь

* Яндекс начал помечать веб-страницы, оптимизированные для работы на смартфонах, знаком «мобильная версия», который будут видеть пользователи мобильного поиска Яндекса (источник: блог для вебмастеров Яндекса)

* Робот Яндекса начал использовать JavaScripts и CSS, что позволяет оценить удобство интерфейса, получить контент, который ранее был недоступен роботу, и сравнить эти данные с уже используемыми при ранжировании в поиске (блог для вебмастеров Яндекса)

* Google позволит запускать Android-приложения напрямую из поиска (источник: vc.ru)

* Яндекс вновь включил ссылочное ранжирование по ряду коммерческих запросов в московском регионе (источник: Searchengines.ru)

* Поисковое приложение Google теперь лучше понимает запросы, включающие прилагательные в превосходной степени, указание конкретного момента времени, а также более сложные вопросы (источник: Searchengines.ru)

* Контент приложения Facebook для Android появится в поисковой выдаче Google (источник: Searchengines.ru)

## Классификация

Можно предложить несколько способов классификации данных событий. На мой взляд, основываясь на имеющихся данных, наиболее удачной будет следующая классификация событий поискового рынка за сентябрь - ноябрь 2015:

* **Поисковая оптимизация**
    * Яндекс будет понижать сайты, злоупотребляющие продажей SEO-ссылок
    * Google обновил поисковый алгоритм – теперь все опасные для пользователей сайты будут исключены из выдачи
    * Яндекс вновь включил ссылочное ранжирование по ряду коммерческих запросов в московском регионе
* **Релевантность поиска**
    * Яндекс тестирует новый подход к определению релевантности документов (эксперементирующий подход)
    * Робот Яндекса начал использовать JavaScripts и CSS
    * Поисковое приложение Google теперь лучше понимает запросы, включающие прилагательные в превосходной степени, указание конкретного момента времени, а также более сложные вопросы
* **Интеграция и сотрудничество**
    * ФАС обязала Google разрешить предустановку приложений Яндекса на Android-смартфоны
    * Яндекс увеличил долю в Турции до 7% за счёт контракта с футболистами «Фенербахче»
    * Yahoo будет показывать результаты поиска от Google
    * Яндекс станет стандартным поисковиком в Windows 10 для России, Турции и ряда стран СНГ
    * Контент приложения Facebook для Android появится в поисковой выдаче Google (источник: Searchengines.ru)
* **Интерфейс**
    * Соцсеть Facebook запустила полноценный поиск по всем опубликованным публичным заметкам
    * Google запустил сервис быстрого просмотра статей прямо в результатах мобильного поиска
    * Яндекс начал помечать веб-страницы, оптимизированные для работы на смартфонах, знаком «мобильная версия», который будут видеть пользователи мобильного поиска Яндекса
    * Google позволит запускать Android-приложения напрямую из поиска
    
Такие ключевые события, как **разрешение предустановки приложения Яндекса на Andriad-смартфоны** (в том числе Яндекс.Поиск) и то, что **Яндекс станет стандартным поисковиком в Windows 10 для России, Турции и ряда стран СНГ** в большой степени повлияют на увеличение аудитории Яндекс.Поиска.

Помимо этого, внедрение новых алгоритмов определения релевантности документов (эксперементирующий и с чтением CSS и Javascript) должно положительно повлиять на количество переходов на сайты из Яндекс.Поиска. 

Также можно сделать предположение о том, что именно мобильная аудитория Яндекс.Поиска в ближайшее время будет активно расти, благодаря выигранному делу против Google и оптимизации поиска под мобильные приложения сайтов.
